### ISSUE TITLE
AC FGC Iteration #1 To-Do

### ISSUE THREAD

**Issue by AtlanticCanadaFGC** [AtlanticCanadaFGC/AtlanticCanadaFGC.github.io#1]
### Code Changes
- [x] Update favicon image
- [x] Update or remove google analytics tags
- [x] Delete SFV Dojo link
- [x] Combine Social Media Section with Tournament Organizers and Streamers sections

### Web Domain

- [ ] Price for AtlanticCanadaFGC domains?
- [x] Alternatively create new github called AtlanticCanadaFGC so the URL is AtlanticCanadaFGC.github.io

### AC Cup Separate Page
- [ ] Embed google sheets for up to date standings
- [ ] Embed google calendar to track events on the circuit
